name: App Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Install, run tests, and build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: proof-of-concept

      - name: Run tests
        run: npm run test
        working-directory: proof-of-concept

      - name: Setup Expo and EAS
        if: ${{ secrets.EXPO_TOKEN }}
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build App
        run: eas build --platform android --profile production --non-interactive --no-wait
        working-directory: proof-of-concept
